#!/usr/bin/env bash
# RUNG 1 STAGE C — link the CuTeDSL AOT object from RUST and prove no Python.
#
# THE GATE, restated: does export_to_c() emit a linkable .o exposing
# __tvm_ffi_<name> that Rust can call, with NO Python at runtime?
#
# Stage A/B (rung1_export.py) produced the object and described the ABI.
# This stage answers the half that actually decides the strategy:
#
#   C1  Rust links the .o and resolves __tvm_ffi_<name>          -> callable
#   C2  the symbol is a TEXT symbol (real code, not a stub)      -> callable
#   C3  the linked binary has NO libpython dependency            -> no Python
#   C4  the binary runs to completion                            -> usable
#
# If all four pass, the FA4->MLA substrate bet is sound and rung 2 can start.
# If C1 or C3 fails, STOP: FlashMLA-per-arch becomes the only road and the
# strategy needs revisiting on this evidence.
#
# Usage:  bash arc-tools/fa4/rung1_link_test.sh
# Reads:  /tmp/arc_fa4_rung1/manifest.json
# Writes: /tmp/arc_fa4_rung1/link_verdict.json

set -uo pipefail

OUT=/tmp/arc_fa4_rung1
MANIFEST="$OUT/manifest.json"
VERDICT="$OUT/link_verdict.json"

C1=fail; C2=fail; C3=fail; C4=fail
NOTE=""

say()  { printf '%s\n' "$*"; }
head2() { printf '\n======================================================================\n%s\n======================================================================\n' "$*"; }

head2 "RUNG 1 STAGE C — Rust link test"

if [ ! -f "$MANIFEST" ]; then
    say "  no manifest at $MANIFEST — run rung1_export.py first"
    exit 2
fi

# ---- pull the object path and the gate symbol out of the manifest ----------
read -r OBJ SYM < <(python3 - "$MANIFEST" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
objs = m.get("artifacts", {}).get("objects") or []
sym = (m.get("verdict") or {}).get("gate_symbol")
# Prefer an object that actually defines the gate symbol.
best = ""
if objs:
    best = objs[0]["path"]
    for o in objs:
        syms = (m.get("symbols", {}).get(o["path"], {}) or {}).get("tvm_ffi") or []
        if syms:
            best = o["path"]
            if not sym:
                sym = syms[0]
            break
print(best or "NONE", sym or "NONE")
PY
)

say "  object: $OBJ"
say "  symbol: $SYM"

if [ "$OBJ" = "NONE" ]; then
    say "  no object emitted — the gate already failed in stage A."
    printf '{"C1":"fail","C2":"fail","C3":"fail","C4":"fail","verdict":"NO_OBJECT__GATE_FAILS"}\n' > "$VERDICT"
    exit 1
fi

# ---- C2: is the symbol real code (nm type T)? ------------------------------
head2 "C2 — symbol is a TEXT symbol (real code)"
if [ "$SYM" != "NONE" ]; then
    LINE=$(nm -g --defined-only "$OBJ" 2>/dev/null | grep -w "$SYM" | head -1)
    say "  $LINE"
    case "$LINE" in
        *" T "*|*" t "*) C2=pass; say "  PASS — text symbol" ;;
        *) say "  FAIL — not a text symbol" ;;
    esac
else
    say "  no __tvm_ffi_* symbol recorded; listing all defined symbols:"
    nm -g --defined-only "$OBJ" 2>/dev/null | head -30
fi

# ---- discover the runtime shared libraries to link against -----------------
head2 "Runtime libraries"
RTLIBS=$(python3 - <<'PY'
import glob, os
try:
    import cutlass
    root = os.path.dirname(cutlass.__file__)
except Exception:
    print(""); raise SystemExit
pats = ["**/libcute_dsl_runtime*.so", "**/*tvm_ffi*.so"]
found = []
for base in (root, os.path.join(root, "..")):
    for p in pats:
        found += glob.glob(os.path.join(base, p), recursive=True)
print("\n".join(sorted(set(os.path.realpath(f) for f in found))))
PY
)
say "${RTLIBS:-  (none found)}"

LINKARGS=()
RPATHS=()
while IFS= read -r lib; do
    [ -z "$lib" ] && continue
    d=$(dirname "$lib")
    b=$(basename "$lib"); b=${b#lib}; b=${b%.so}
    LINKARGS+=( -C "link-arg=-L$d" -C "link-arg=-l$b" )
    RPATHS+=( -C "link-arg=-Wl,-rpath,$d" )
done <<< "$RTLIBS"

# CUDA driver — the kernel object will reference it.
for cd in /usr/lib/x86_64-linux-gnu /usr/local/cuda/lib64 /usr/local/cuda/lib64/stubs; do
    [ -d "$cd" ] && LINKARGS+=( -C "link-arg=-L$cd" )
done
LINKARGS+=( -C "link-arg=-lcuda" )

# ---- C1: generate a Rust harness and link it -------------------------------
head2 "C1 — Rust links the object and resolves the symbol"

if ! command -v rustc >/dev/null 2>&1; then
    say "  rustc not found — cannot run the decisive half of the gate."
    printf '{"C1":"skip","verdict":"NO_RUSTC"}\n' > "$VERDICT"
    exit 2
fi

HARNESS="$OUT/harness.rs"
if [ "$SYM" != "NONE" ]; then
cat > "$HARNESS" <<RS
// Generated by rung1_link_test.sh — do not edit.
//
// Proves the CuTeDSL AOT object is reachable from Rust's FFI: we declare the
// exported symbol, take its address through a raw pointer, and confirm the
// linker resolved it to something non-null. Taking the address (rather than
// calling) is deliberate — invoking it needs the TVM FFI argument pack, which
// is rung 2. What rung 1 must establish is that the symbol EXISTS, LINKS, and
// needs no Python interpreter to do so.
extern "C" {
    fn $SYM();
}

fn main() {
    let addr = $SYM as *const ();
    println!("symbol  = $SYM");
    println!("address = {addr:p}");
    assert!(!addr.is_null(), "symbol resolved to null");
    println!("ARC_RUNG1_LINK_OK");
}
RS
else
cat > "$HARNESS" <<'RS'
fn main() { println!("ARC_RUNG1_NO_SYMBOL"); }
RS
fi

BIN="$OUT/harness"
say "  rustc $HARNESS -> $BIN"
set -x
rustc "$HARNESS" -O -o "$BIN" \
    -C "link-arg=$OBJ" \
    "${LINKARGS[@]}" "${RPATHS[@]}" 2> "$OUT/rustc.log"
RC=$?
set +x
if [ $RC -eq 0 ]; then
    C1=pass; say "  PASS — linked"
else
    say "  FAIL — link error (tail of $OUT/rustc.log):"
    tail -40 "$OUT/rustc.log" | sed 's/^/    /'
fi

# ---- C3: no Python in the linked binary ------------------------------------
head2 "C3 — the binary does NOT depend on libpython"
if [ -x "$BIN" ]; then
    LDD=$(ldd "$BIN" 2>/dev/null)
    say "$LDD" | sed 's/^/    /'
    if printf '%s' "$LDD" | grep -qi 'libpython'; then
        say "  FAIL — libpython is linked in; this would put Python in the serving path."
    else
        C3=pass; say "  PASS — no libpython"
    fi
else
    say "  (no binary to inspect)"
fi

# ---- C4: it runs -----------------------------------------------------------
head2 "C4 — the binary runs"
if [ -x "$BIN" ]; then
    RUNOUT=$("$BIN" 2>&1); RRC=$?
    say "$RUNOUT" | sed 's/^/    /'
    if [ $RRC -eq 0 ] && printf '%s' "$RUNOUT" | grep -q ARC_RUNG1_LINK_OK; then
        C4=pass; say "  PASS — exit 0"
    else
        say "  FAIL — exit $RRC"
    fi
fi

# ---- verdict ---------------------------------------------------------------
head2 "RUNG 1 VERDICT"
if [ "$C1" = pass ] && [ "$C3" = pass ] && [ "$C4" = pass ]; then
    V="GATE_PASSES__export_to_c_is_linkable_from_rust_without_python"
    NOTE="Proceed to rung 2 (vanilla FA4 callable from Arc)."
elif [ "$C1" = pass ] && [ "$C3" != pass ]; then
    V="LINKS_BUT_DRAGS_PYTHON__investigate"
    NOTE="Object links but pulls libpython. Check whether that is the harness or the runtime .so."
else
    V="GATE_FAILS__no_rust_callable_object"
    NOTE="STOP AND REPORT. FlashMLA-per-arch becomes the only road; the strategy needs revisiting on this evidence."
fi

say "  C1 link=$C1  C2 text-symbol=$C2  C3 no-python=$C3  C4 runs=$C4"
say "  => $V"
say "  $NOTE"

cat > "$VERDICT" <<JSON
{
  "schema": "arc.fa4_rung1_link/1",
  "object": "$OBJ",
  "symbol": "$SYM",
  "C1_rust_links": "$C1",
  "C2_text_symbol": "$C2",
  "C3_no_libpython": "$C3",
  "C4_runs": "$C4",
  "verdict": "$V",
  "note": "$NOTE"
}
JSON
say ""
say "  verdict: $VERDICT"
[ "$V" = "GATE_PASSES__export_to_c_is_linkable_from_rust_without_python" ] && exit 0 || exit 1
